name: Test
run-name: Test (${{ github.actor }})
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Setup Environment
        run: echo "SQLITE_DB=:memory:" >> $GITHUB_ENV
      - run: go test ./...
